Cleaned up excess whitespace

diff --git a/roles/tekton-pipeline/templates/tasks.yml.j2 b/roles/tekton-pipeline/templates/tasks.yml.j2
--- a/roles/tekton-pipeline/templates/tasks.yml.j2
+++ b/roles/tekton-pipeline/templates/tasks.yml.j2
@@ -198,40 +198,40 @@
 
           set -e -o pipefail
 
-          echo "Creating new build config"  
+          echo "Creating new build config"
 
           GITSHA=$(cat
-          $(inputs.resources.source.path)/$(params.app_name)-gitsha.txt)  
+          $(inputs.resources.source.path)/$(params.app_name)-gitsha.txt)
 
 
-          echo "Extracted git revision from previous step $GITSHA" 
+          echo "Extracted git revision from previous step $GITSHA"
 
           # This allows the new build to be created whether it exists or not
 
           oc new-build -o yaml --name=$(params.app_name) --image-stream=jboss-eap72-openshift:1.1  --binary=true -n
-          $(params.dev_project) | oc apply -n $(params.dev_project) -f - 
+          $(params.dev_project) | oc apply -n $(params.dev_project) -f -
       - name: build-app-image
-        image: 'quay.io/openshift/origin-cli:latest'    
+        image: 'quay.io/openshift/origin-cli:latest'
         script: >
           #!/bin/sh
 
           set -e -o pipefail
 
-          echo "Start the openshift build"  
+          echo "Start the openshift build"
 
 
-          rm -rf $(inputs.resources.source.path)/oc-build && mkdir -p $(inputs.resources.source.path)/oc-build/deployments 
+          rm -rf $(inputs.resources.source.path)/oc-build && mkdir -p $(inputs.resources.source.path)/oc-build/deployments
 
 
-          cp $(workspaces.maven-repo.path)/$(params.artifact_path) $(inputs.resources.source.path)/oc-build/deployments/ROOT.war 
+          cp $(workspaces.maven-repo.path)/$(params.artifact_path) $(inputs.resources.source.path)/oc-build/deployments/ROOT.war
 
 
-          oc start-build $(params.app_name) --from-dir=$(inputs.resources.source.path)/oc-build -n   $(params.dev_project) --wait=true 
+          oc start-build $(params.app_name) --from-dir=$(inputs.resources.source.path)/oc-build -n   $(params.dev_project) --wait=true
 
-          GITSHA=$(cat $(inputs.resources.source.path)/$(params.app_name)-gitsha.txt) 
+          GITSHA=$(cat $(inputs.resources.source.path)/$(params.app_name)-gitsha.txt)
 
 
-          oc tag $(params.app_name):latest  $(params.app_name):$GITSHA -n $(params.dev_project) 
+          oc tag $(params.app_name):latest  $(params.app_name):$GITSHA -n $(params.dev_project)
 
           echo "Successfully created container image $(params.dev_project)/$(params.app_name):$GITSHA"
     workspaces:
@@ -239,7 +239,7 @@
 {# Start new tasks breakout:
     TODO
     ------
-    - Modify pipeline to consume the new tasks 
+    - Modify pipeline to consume the new tasks
     - Inject pvc for `report` workspace for oscap-image-scan task
     -------
     Done
@@ -277,23 +277,23 @@
 
           set -e -o pipefail
 
-          echo "Create new app from tasks image stream in $(params.dev_project) project"   
+          echo "Create new app from tasks image stream in $(params.dev_project) project"
 
-          GITSHA=$(cat $(inputs.resources.source.path)/$(params.app_name)-gitsha.txt) 
+          GITSHA=$(cat $(inputs.resources.source.path)/$(params.app_name)-gitsha.txt)
 
           oc new-app --image-stream=$(params.app_name):$GITSHA -n
-          $(params.dev_project) --as-deployment-config=true -o yaml | oc apply -n $(params.dev_project)  -f - 
+          $(params.dev_project) --as-deployment-config=true -o yaml | oc apply -n $(params.dev_project)  -f -
 
           echo "Setting manual triggers on deployment $(params.app_name)"
 
-          oc set triggers dc/$(params.app_name) --manual=true -n  $(params.dev_project) 
+          oc set triggers dc/$(params.app_name) --manual=true -n  $(params.dev_project)
 
           if ! oc get route/$(params.app_name) -n $(params.dev_project) ; then
 
             oc expose svc $(params.app_name) -n $(params.dev_project) || echo "Failed to create route for $(params.app_name)"
 
           fi
-            
+
           oc rollout latest dc/$(params.app_name) -n  $(params.dev_project)
     workspaces:
       - name: maven-repo
@@ -314,14 +314,14 @@
           type: git
     steps:
       - name: announce
-        image: 'gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:latest'      
+        image: 'gcr.io/tekton-releases/github.com/tektoncd/pipeline/cmd/git-init:latest'
         script: >
           #!/bin/sh
 
           set -e -o pipefail
 
           GITSHA=$(cat
-          $(inputs.resources.source.path)/$(params.app_name)-gitsha.txt) 
+          $(inputs.resources.source.path)/$(params.app_name)-gitsha.txt)
           &&
 
           echo "Successfully build application $(params.app_name)"
@@ -341,7 +341,7 @@
       description: The oscap xccdf profile to use when calling the oscap-chroot command
       default: xccdf_org.ssgproject.content_profile_standard
     - name: oscapProfilePath
-      description: The full path to the oscap content file 
+      description: The full path to the oscap content file
       default: /usr/share/xml/scap/ssg/content/ssg-centos7-ds-1.2.xml
     - name: container-imagetag
       type: string
@@ -403,18 +403,18 @@
 
         set -e -o pipefail
 
-        echo "Tagging image stream in 
-        $(params.stage_project)/$(params.app_name):$(params.app_revision)"          
+        echo "Tagging image stream in
+        $(params.stage_project)/$(params.app_name):$(params.app_revision)"
 
         oc tag
         $(params.dev_project)/$(params.app_name):$(params.app_revision)
-        $(params.stage_project)/$(params.app_name):$(params.app_revision)          
+        $(params.stage_project)/$(params.app_name):$(params.app_revision)
 
         if oc get dc/$(params.app_name) -n $(params.stage_project); then
 
-          echo "Tasks dc exists, cleaning up resources " 
-          
-          oc delete -n $(params.stage_project) dc/$(params.app_name) svc/$(params.app_name) route/$(params.app_name) || echo "Some resources didn't clean up as expected"; 
+          echo "Tasks dc exists, cleaning up resources "
+
+          oc delete -n $(params.stage_project) dc/$(params.app_name) svc/$(params.app_name) route/$(params.app_name) || echo "Some resources didn't clean up as expected";
 
         fi
 
@@ -426,19 +426,19 @@
 
         set -e -o pipefail
 
-        echo "Deploying new version into $(params.stage_project)  project "  
+        echo "Deploying new version into $(params.stage_project)  project "
 
-        oc new-app --image-stream=$(params.app_name):$(params.app_revision) -n $(params.stage_project) 
-        --as-deployment-config=true -o yaml  | oc apply -n $(params.stage_project)  -f -   
+        oc new-app --image-stream=$(params.app_name):$(params.app_revision) -n $(params.stage_project)
+        --as-deployment-config=true -o yaml  | oc apply -n $(params.stage_project)  -f -
 
 
         if ! oc get route/$(params.app_name) -n $(params.stage_project) ; then
-          
-          echo "Route not found, creating a new one" 
 
-          oc expose svc $(params.app_name) -n  $(params.stage_project); 
+          echo "Route not found, creating a new one"
 
-        fi  
+          oc expose svc $(params.app_name) -n  $(params.stage_project);
+
+        fi
 
       image: 'quay.io/openshift/origin-cli:latest'
 {% endfor %}
